default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development_portfolio

test:
  <<: *default
  database: test_portfolio

production:
  <<: *default
  database: production_portfolio
