# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a11d0cd0adf3cfbfd646edeea7bd216fc07012e546db92d314ae875450b62373c22055e031931b2696aee48d2b4fb3fb929574354d88f47b182ea1152873f2f

test:
  secret_key_base: 59b29dcab2fa30c160e7fd72c52b3620a1766e109bf17271f62ef93bd4e084b7047dd8aaf99bcdff789a33bd6321a36500f8233a9dfb35868e56133efd7ddb3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
